// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/booking.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/booking.go -destination=tests/mocks/mock_db.go -package=mocks DB
//

// Package mocks is a generated GoMock package.
package mocks

import (
	publisher "booking-service/internal/publisher"
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// PublishBookingCancelled mocks base method.
func (m *MockEventPublisher) PublishBookingCancelled(ctx context.Context, event *publisher.BookingCancelledEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBookingCancelled", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBookingCancelled indicates an expected call of PublishBookingCancelled.
func (mr *MockEventPublisherMockRecorder) PublishBookingCancelled(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBookingCancelled", reflect.TypeOf((*MockEventPublisher)(nil).PublishBookingCancelled), ctx, event)
}

// PublishBookingCreated mocks base method.
func (m *MockEventPublisher) PublishBookingCreated(ctx context.Context, event *publisher.BookingCreatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishBookingCreated", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishBookingCreated indicates an expected call of PublishBookingCreated.
func (mr *MockEventPublisherMockRecorder) PublishBookingCreated(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishBookingCreated", reflect.TypeOf((*MockEventPublisher)(nil).PublishBookingCreated), ctx, event)
}

// PublishPaymentConfirmed mocks base method.
func (m *MockEventPublisher) PublishPaymentConfirmed(ctx context.Context, event *publisher.PaymentConfirmedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPaymentConfirmed", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPaymentConfirmed indicates an expected call of PublishPaymentConfirmed.
func (mr *MockEventPublisherMockRecorder) PublishPaymentConfirmed(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPaymentConfirmed", reflect.TypeOf((*MockEventPublisher)(nil).PublishPaymentConfirmed), ctx, event)
}

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDB) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockDBMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDB)(nil).Begin), ctx)
}
