// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/booking.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/booking.go -destination=tests/mocks/mock_booking.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "booking-service/internal/domain"
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
	isgomock struct{}
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// AdminListAll mocks base method.
func (m *MockBookingRepository) AdminListAll(ctx context.Context, limit, offset int) ([]*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminListAll", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminListAll indicates an expected call of AdminListAll.
func (mr *MockBookingRepositoryMockRecorder) AdminListAll(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminListAll", reflect.TypeOf((*MockBookingRepository)(nil).AdminListAll), ctx, limit, offset)
}

// Cancel mocks base method.
func (m *MockBookingRepository) Cancel(ctx context.Context, tx pgx.Tx, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockBookingRepositoryMockRecorder) Cancel(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockBookingRepository)(nil).Cancel), ctx, tx, id)
}

// Create mocks base method.
func (m *MockBookingRepository) Create(ctx context.Context, tx pgx.Tx, booking *domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBookingRepositoryMockRecorder) Create(ctx, tx, booking any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBookingRepository)(nil).Create), ctx, tx, booking)
}

// GetByID mocks base method.
func (m *MockBookingRepository) GetByID(ctx context.Context, id string) (*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBookingRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBookingRepository)(nil).GetByID), ctx, id)
}

// GetHistory mocks base method.
func (m *MockBookingRepository) GetHistory(ctx context.Context, userID string) ([]*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, userID)
	ret0, _ := ret[0].([]*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockBookingRepositoryMockRecorder) GetHistory(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockBookingRepository)(nil).GetHistory), ctx, userID)
}

// GetStats mocks base method.
func (m *MockBookingRepository) GetStats(ctx context.Context) (int64, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetStats indicates an expected call of GetStats.
func (mr *MockBookingRepositoryMockRecorder) GetStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockBookingRepository)(nil).GetStats), ctx)
}

// ListByUserID mocks base method.
func (m *MockBookingRepository) ListByUserID(ctx context.Context, userID string) ([]*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockBookingRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockBookingRepository)(nil).ListByUserID), ctx, userID)
}

// UpdateStatus mocks base method.
func (m *MockBookingRepository) UpdateStatus(ctx context.Context, id, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockBookingRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockBookingRepository)(nil).UpdateStatus), ctx, id, status)
}
