{
 "title": "Movie Service",
 "tags": [
  "cinema",
  "movie-service"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "gRPC Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{job=\"movie-service\"}[1m])",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(redis_hits_total{job=\"movie-service\"}[5m]) / (rate(redis_hits_total{job=\"movie-service\"}[5m]) + rate(redis_misses_total{job=\"movie-service\"}[5m])) * 100",
     "legendFormat": "Hit %"
    }
   ]
  },
  {
   "title": "DB Query Duration p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(db_query_duration_seconds_bucket{job=\"movie-service\"}[5m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"movie-service\"}"
    }
   ]
  }
 ]
}