{
 "title": "Notification Service",
 "tags": [
  "cinema",
  "notification-service"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Emails Sent/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(emails_sent_total{job=\"notification-service\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total Emails Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "emails_sent_total{job=\"notification-service\",status=\"success\"}"
    }
   ]
  },
  {
   "title": "Failed Emails",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "emails_sent_total{job=\"notification-service\",status=\"failed\"}"
    }
   ]
  },
  {
   "title": "NATS Messages Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(nats_messages_consumed_total{job=\"notification-service\"}[1m])",
     "legendFormat": "{{subject}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{service=\"notification-service\"}"
    }
   ]
  }
 ]
}