run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - bodyclose

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment

issues:
  exclude-rules:
    - path: gen/
      linters:
        - all
    - path: internal/repository/mocks/
      linters:
        - all
